import type { ChordQuality, ChordExtensions, MusicalKey, Mode, ScaleDegree, Chord } from './chord';

// Style references for composer personalities
export type StyleReference = 'lauridsen' | 'part' | 'whitacre' | 'bach' | 'debussy' | 'general';

// Emotional phase mapping from narrative to music
export interface NarrativePhase {
  phase: string;
  description: string;
}

// Single chord as generated by AI
export interface GeneratedChordData {
  scaleDegree: ScaleDegree;
  quality: ChordQuality;
  extensions?: ChordExtensions;
  duration: number;  // in beats
  phase: string;     // which emotional phase this belongs to
}

// Complete result from AI generation
export interface NarrativeResult {
  key: MusicalKey;
  mode: Mode;
  chords: GeneratedChordData[];
  explanation: string;
  emotionalMapping: NarrativePhase[];
}

// Options for the composer
export interface ComposerOptions {
  styleReference: StyleReference;
  barCount: number;  // 4, 8, 16, or 32
  beatsPerBar: number;
}

// Error types for the narrative composer
export type NarrativeComposerError =
  | 'api_error'
  | 'rate_limit'
  | 'invalid_response'
  | 'validation_error'
  | 'empty_narrative'
  | 'generation_failed';

// Result type for the conversion
export interface NarrativeConversionResult {
  chords: Chord[];
  explanation: string;
  emotionalMapping: NarrativePhase[];
}
